[[block]]
block = "time"				# Date / Time block
format = "%a %F %I:%M %p"
interval = 60

[[block]]
block = "bluetooth"			# BT block
#mac = "00:00:46:03:37:01"	# Laptop
mac = "FC:A8:9A:A2:12:9A"	# Earphones

[[block]]
block = "cpu"				# CPU usage block
interval = 5
format = "{barchart}{utilization}% {frequency}Ghz"

[[block]]
block = "disk_space"		# Disk space usage block
path = "/"
alias = "ROOT"
info_type = "available"
unit = "GB"
interval = 30

#[[block]]
#block = "keyboard_layout"	# Keyboard layout block
#driver = "localebus"		# Driver = setxkbmap / localebus
#interval = 10

#[[block]]
#block = "music"				# Music control block
#player = "playerctl"
#buttons = ["play", "next"]

[[block]]
block = "net"				# Network block
device = "enp4s0"
ip = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 5

[[block]]
block = "pacman"			# Pacman update checking block
interval = 300

[[block]]
block = "sound"				# Volume control block
step_width = 5				# Volume step
driver = "auto"				# Driver = auto / pulseaudio / alsa

[[block]]
block = "memory"			# Memory / Swap usage block
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"		# Display 
icons = true
clickable = true			# Toggle view by click on Memory / Swap
interval = 10
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "backlight"
device = "intel_backlight"

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{min}° min, {max}° max, {average}° avg"
#chip = "coretemp-isa-0000"	# Chip name in sensors -u

#[[block]]
#block = "uptime"			# System uptime block
